/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupervisorRole;

import Business.Enterprise.Enterprise;
import Business.Locations.PopulateLocations;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.staffOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WaterTestingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anuja
 */
public class RequestWaterTestJPanel extends javax.swing.JPanel {
    
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private Enterprise enterprise;
    private PopulateLocations popLocations;
    /**
     * Creates new form RequestWaterTestJPanel
     */
    RequestWaterTestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.network=network;
        popLocations = new PopulateLocations(network, enterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        waterdeptlbl = new javax.swing.JLabel();
        supdashlbl = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        indRadioBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        resRadioBtn = new javax.swing.JRadioButton();
        locationjCombobox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requestTestJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        waterdeptlbl.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        waterdeptlbl.setText("Water Department");

        supdashlbl.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        supdashlbl.setText("  Supervisor Dashboard");

        areaLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        areaLabel.setText("Area");

        indRadioBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        indRadioBtn.setText("Industrial");
        indRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indRadioBtnActionPerformed(evt);
            }
        });

        msgTextArea.setColumns(20);
        msgTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        msgTextArea.setRows(5);
        jScrollPane1.setViewportView(msgTextArea);

        resRadioBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        resRadioBtn.setText("Residential");
        resRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resRadioBtnActionPerformed(evt);
            }
        });

        locationjCombobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Location");

        backJButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Message");

        requestTestJButton.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supdashlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterdeptlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(indRadioBtn)
                        .addGap(30, 30, 30)
                        .addComponent(resRadioBtn)
                        .addGap(211, 211, 211)))
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(32, 32, 32)
                        .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(locationjCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(waterdeptlbl)
                        .addGap(29, 29, 29)
                        .addComponent(supdashlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indRadioBtn)
                    .addComponent(resRadioBtn))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationjCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void indRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indRadioBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> waterLocations = popLocations.populateWaterLocations(network, enterprise, true, false);

        locationjCombobox.removeAllItems();
        for (String waterLocation : waterLocations) {
            locationjCombobox.addItem(waterLocation);
        }
    }//GEN-LAST:event_indRadioBtnActionPerformed

    private void resRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resRadioBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> waterLocations = popLocations.populateWaterLocations(network, enterprise, false, true);

        locationjCombobox.removeAllItems();
        for (String waterLocation : waterLocations) {
            locationjCombobox.addItem(waterLocation);
        }
    }//GEN-LAST:event_resRadioBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SupervisorWorkAreaJPanel dwjp = (SupervisorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

         String message = msgTextArea.getText();
        String location = locationjCombobox.getSelectedItem().toString();

        if (message.length() == 0 && (location.equals("") || (location == null))) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        WaterTestingWorkRequest request = new WaterTestingWorkRequest();
        
        //Set the message
        request.setMessage(message);
        request.setSender(userAccount);
        request.setEnterprise(enterprise);
        request.setNetwork(network);
         //Select the location as per sent request
         
        if(indRadioBtn.isSelected())
        {
             request.setArea(indRadioBtn.getText());
        }
        else
        {
            request.setArea(resRadioBtn.getText());  
        }
        
        request.setLocation(String.valueOf(locationjCombobox.getSelectedItem()));
        request.setStatus("Sent");
        
        Organization org = null;
        Enterprise   e = enterprise;
     
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList())
        {
            if (organization instanceof staffOrganisation){
                org = organization;
                break;
            }
        }
      
        if (org!=null)
        {
          org.getWorkQueue().getWorkRequestList().add(request);
          userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
      
        JOptionPane.showMessageDialog(null,"Request raised","Success",JOptionPane.INFORMATION_MESSAGE);     
        
        msgTextArea.setText("");
        buttonGroup1.clearSelection();
        locationjCombobox.removeAllItems();;
    }//GEN-LAST:event_requestTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton indRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox locationjCombobox;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JRadioButton resRadioBtn;
    private javax.swing.JLabel supdashlbl;
    private javax.swing.JLabel waterdeptlbl;
    // End of variables declaration//GEN-END:variables
}
