/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupervisorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WaterTestingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import Business.EcoSystem;
import Business.AlertQueue.AlertList.*;
import Business.WorkQueue.SoilTestWorkRequest;
import userinterface.StaffRole.ProcessWaterWorkRequestJPanel;

/**
 *
 * @author raunak
 */
public class SupervisorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private supervisorOrganisation organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    LabTestWorkRequest request1;
    SoilTestWorkRequest request2;
    WaterTestingWorkRequest requestWrk;
    private EcoSystem business;
    private WaterTestingWorkRequest requestWaterTest;
	 
    public SupervisorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, supervisorOrganisation organization, Enterprise enterprise,Network network,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.network = network;
        valueLabel.setText(enterprise.getName());
        nameJLabel.setText(account.getEmployee().getName().toUpperCase());
        populateRequestTable();
        VisibleButtons();
        jPanel1.setVisible(false);
       
    }
   
    public void VisibleButtons()
    {
        ForwardJButton2.setEnabled(false);
        ViewJButton1.setEnabled(false);
        if(enterprise.getEnterpriseType().toString().equals("Municipal"))
        {
            ForwardJButton2.setVisible(false);
            ViewJButton1.setVisible(false);
            jButtonSolution.setVisible(true);
        }
        else
        {
            ForwardJButton2.setVisible(true);  
            ViewJButton1.setVisible(true);
             jButtonSolution.setVisible(false);
        }
        //added by Anuja
//        if(enterprise.getEnterpriseType().toString().equals("Lab")){
//            labTestProceedBtn.setVisible(true);
//            requestTestJButton.setVisible(false);
//        }
//        else{
//            labTestProceedBtn.setVisible(false);
//            requestTestJButton.setVisible(true);
//        }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getReceiver();
            
            row[2] = request.getStatus();
            String result = "View";
          //  row[3] = result == null ? "Waiting" : result;
             row[3] = request.getSender();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        ViewJButton1 = new javax.swing.JButton();
        ForwardJButton2 = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        nameJLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        jButtonSolution = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        enterpriseLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        workRequestJTable.setBackground(new java.awt.Color(255, 255, 204));
        workRequestJTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workRequestJTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                workRequestJTableMousePressed(evt);
            }
        });
        workRequestJTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                workRequestJTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        ViewJButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        ViewJButton1.setText("View");
        ViewJButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJButton1ActionPerformed(evt);
            }
        });

        ForwardJButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        ForwardJButton2.setText("Forward");
        ForwardJButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ForwardJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardJButton2ActionPerformed(evt);
            }
        });

        requestTestJButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        refreshTestJButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        nameJLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        nameJLabel.setText("<value>");

        enterpriseLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Name");

        jButtonSolution.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonSolution.setText("Solution");
        jButtonSolution.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSolution.setEnabled(false);
        jButtonSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolutionActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alert Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Message");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Alert Received");

        jToggleButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jToggleButton1.setText("Close");
        jToggleButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("View Alert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(ForwardJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(ViewJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameJLabel)
                    .addComponent(enterpriseLabel1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForwardJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workRequestJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workRequestJTableMouseClicked
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, "Select all click", "Icomplete", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_workRequestJTableMouseClicked

    private void workRequestJTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workRequestJTableMousePressed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if(selectedRow < 0)
        {
            return;
        }
        UserAccount sender = (UserAccount)workRequestJTable.getValueAt(selectedRow, 3);
        String user = sender.getUsername();
        //   System.out.print(sender);
        if (user.contains("mun"))
        {
            ForwardJButton2.setEnabled(true);
        }
        else
        {
            ForwardJButton2.setEnabled(false);
        }

        String status = workRequestJTable.getValueAt(selectedRow,2).toString();
        
        if(status.contains("Complete") || status.contains("Completed"))
        {
            //System.out.println("hi");
            ViewJButton1.setEnabled(true);
             ForwardJButton2.setEnabled(false);
        }
        else if(status.contains("Sent By Lab"))
        {
            ViewJButton1.setEnabled(true);
        }
        else if(status.contains("Alert"))
        {
            ViewJButton1.setEnabled(true);
        }
        else
             ViewJButton1.setEnabled(false);
        
        if(status.contains("Solved"))
        {
            jButtonSolution.setEnabled(true);
        }
        else
        {
             jButtonSolution.setEnabled(false);
        }
    }//GEN-LAST:event_workRequestJTableMousePressed

    private void workRequestJTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workRequestJTableKeyPressed
        // TODO add your handling code here:
        //   JOptionPane.showMessageDialog(null, "Select all", "Icomplete", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_workRequestJTableKeyPressed

    private void ViewJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJButton1ActionPerformed
        // TODO add your handling code here:
        //   DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("air"))
        {
            request1 = (LabTestWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);

            //WorkRequest request = null;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ProcessWorkView", new ProcessWorkViewJPanel(userProcessContainer, userAccount, enterprise,network,request1));
            layout.next(userProcessContainer);
        }
		
        if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Water")) {
            //System.out.println("SupWorkArea - ViewJButton1ActionPerformed Network WATER ");

            requestWaterTest = (WaterTestingWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ProcessWorkView", new ViewWaterWorkReadingsJPanel(userProcessContainer, userAccount, enterprise, network, requestWaterTest));
            layout.next(userProcessContainer);
        }
		
        //If its a soil enterprise process the request
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("soil"))
        {
            request2 = (SoilTestWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
            CardLayout layout2 = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ProcessSoilWorkView", new ProcessSoilWorkViewJPanel(userProcessContainer, userAccount, enterprise,network,request2));
            layout2.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_ViewJButton1ActionPerformed

    private void ForwardJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardJButton2ActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        //Forward the request for air enterprise to staff
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("air"))
        {
            request1 = (LabTestWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ForwardrequestJPanel1", new ForwardrequestJPanel1(userProcessContainer, userAccount, enterprise,network,request1));
            layout.next(userProcessContainer);
        }
        
        //Forward the request for soil enterprise to staff
        if(enterprise.getEnterpriseType().getValue().equals("Soil"))
        {
            request2 = (SoilTestWorkRequest)workRequestJTable.getValueAt(selectedRow,0);
            CardLayout layout2 = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ForwardSoilRequestJPanel", new ForwardSoilRequestJPanel(userProcessContainer, userAccount, enterprise,network,request2));
            layout2.next(userProcessContainer);
            
        }
        if(enterprise.getEnterpriseType().getValue().equals("Water"))
        {
            requestWrk = (WaterTestingWorkRequest)workRequestJTable.getValueAt(selectedRow,0);
            CardLayout layout2 = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ForwardWaterRequestJPanel1", new ForwardWaterRequestJPanel1(userProcessContainer, userAccount, enterprise,network,requestWrk));
            layout2.next(userProcessContainer);
            
        }
    }//GEN-LAST:event_ForwardJButton2ActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        if((enterprise.getEnterpriseType().getValue().equalsIgnoreCase("air"))||(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("municipal")))
        {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterprise,network));
            layout.next(userProcessContainer);    
        }
     
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Water"))
        {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestLabTestJPanel", new RequestWaterTestJPanel(userProcessContainer, userAccount, enterprise, network));
            layout.next(userProcessContainer); 
        }
        
        //Create a request for Soil Test
        if(enterprise.getEnterpriseType().getValue().equals("Soil"))
        {
            CardLayout layout2 = (CardLayout) userProcessContainer.getLayout();
           userProcessContainer.add("RequestSoilTestJPanel", new RequestSoilTestJPanel(userProcessContainer, userAccount, enterprise,network));
           layout2.next(userProcessContainer);          
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void jButtonSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolutionActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
       
           
      WorkRequest      request1 = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);

            //WorkRequest request = null;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("Solutionview", new Solutionview(userProcessContainer, userAccount, enterprise,network,request1));
            layout.next(userProcessContainer);
      
        
    }//GEN-LAST:event_jButtonSolutionActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
        WorkRequest req = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        
        if(req.getStatus().contains("Alert"))
        {
            req.setStatus("Acknowledged");
            jPanel1.setVisible(true);
            jTextArea1.setText(req.getMessage());   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForwardJButton2;
    private javax.swing.JButton ViewJButton1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSolution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
