/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupervisorRole;

import Business.Analysis.PopulateChart;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WaterTestingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFrame;
import userinterface.StaffRole.ProcessWaterWorkRequestJPanel;

/**
 *
 * @author Anuja
 */
public class ViewWaterReadingsJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private Enterprise enterprise;
    private Network network;
    private WaterTestingWorkRequest request;
    private JPanel userProcessContainer;
    PopulateChart populatechart;
    /**
     * Creates new form ViewWaterWorkReadingsJPanel
     */
    public ViewWaterReadingsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network, WaterTestingWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
        this.request = request;
        this.populatechart = new PopulateChart();
        
        leadSpinner.setEnabled(false);
        mercurySpinner.setEnabled(false);
        crudeOilSpinner.setEnabled(false);
        plasticSpinner.setEnabled(false);
        uraniumSpinner.setEnabled(false);
        populateValues();
        populateLabResults();
    }
    
    public void populateLabResults()
    {
        leadSpinner.setEnabled(false);
        mercurySpinner.setEnabled(false);
        crudeOilSpinner.setEnabled(false);
        plasticSpinner.setEnabled(false);
        uraniumSpinner.setEnabled(false);
        
        leadSpinner.setValue(request.getLeadReading());
        mercurySpinner.setValue(request.getMercuryReading());
        crudeOilSpinner.setValue(request.getCrudeOilReading());
        plasticSpinner.setValue(request.getPlasticReading());
        uraniumSpinner.setValue(request.getUraniumReading());
    }

    public void populateValues(){
        txtLocaton.setText(request.getLocation());
        txtQuantity.setText(request.getQuantity());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        EmployeeWorkArealbl = new javax.swing.JLabel();
        PageTitlelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leadlbl = new javax.swing.JLabel();
        leadSpinner = new javax.swing.JSpinner();
        mercurylbl = new javax.swing.JLabel();
        mercurySpinner = new javax.swing.JSpinner();
        oillbl = new javax.swing.JLabel();
        crudeOilSpinner = new javax.swing.JSpinner();
        plasticlbl = new javax.swing.JLabel();
        plasticSpinner = new javax.swing.JSpinner();
        uraniumlbl = new javax.swing.JLabel();
        uraniumSpinner = new javax.swing.JSpinner();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLocaton = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(153, 255, 255));

        EmployeeWorkArealbl.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        EmployeeWorkArealbl.setText("HeadScientist DashBoard");

        PageTitlelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("                     FIELD DATA");

        leadlbl.setText("Lead : ");

        leadSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leadSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

        mercurylbl.setText("Mercury :");

        mercurySpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mercurySpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

        oillbl.setText("Crude Oil : ");

        crudeOilSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudeOilSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

        plasticlbl.setText("Plastic :");

        plasticSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plasticSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

        uraniumlbl.setText("Uranium : ");

        uraniumSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uraniumSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

        backButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Location:");

        jLabel3.setText("Quantity:");

        txtLocaton.setEditable(false);
        txtLocaton.setEnabled(false);

        txtQuantity.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(387, 387, 387)
                            .addComponent(PageTitlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(316, 316, 316)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtLocaton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(31, 31, 31)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(356, 356, 356)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(plasticlbl)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oillbl)
                                    .addComponent(mercurylbl)
                                    .addComponent(leadlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(uraniumlbl))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(plasticSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(crudeOilSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uraniumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mercurySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(leadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(378, 378, 378)
                            .addComponent(EmployeeWorkArealbl, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PageTitlelbl)
                .addGap(18, 18, 18)
                .addComponent(EmployeeWorkArealbl)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLocaton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mercurylbl)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leadlbl))
                        .addGap(29, 29, 29)
                        .addComponent(mercurySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oillbl)
                    .addComponent(crudeOilSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plasticlbl)
                    .addComponent(plasticSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uraniumlbl)
                    .addComponent(uraniumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabHeadScientistJPanel dwjp = (LabHeadScientistJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeWorkArealbl;
    private javax.swing.JLabel PageTitlelbl;
    private javax.swing.JButton backButton;
    private javax.swing.JSpinner crudeOilSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner leadSpinner;
    private javax.swing.JLabel leadlbl;
    private javax.swing.JSpinner mercurySpinner;
    private javax.swing.JLabel mercurylbl;
    private javax.swing.JLabel oillbl;
    private javax.swing.JSpinner plasticSpinner;
    private javax.swing.JLabel plasticlbl;
    private javax.swing.JTextField txtLocaton;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JSpinner uraniumSpinner;
    private javax.swing.JLabel uraniumlbl;
    // End of variables declaration//GEN-END:variables
}
