/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WaterTestingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anuja
 */
public class ProcessLabWorkRequestForWater extends javax.swing.JPanel {

    private WaterTestingWorkRequest request;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization staffOrganisation;
    private Enterprise enterprise;
    private Network network;
    //private JPanel userProcessContainer;
    /**
     * Creates new form ProcessLabWorkRequestForWater
     */

    ProcessLabWorkRequestForWater(JPanel userProcessContainer, UserAccount account, Organization staffOrganisation, Enterprise enterprise,  Network network, WaterTestingWorkRequest request) {
        initComponents();
        this.request=request;
        this.userProcessContainer = userProcessContainer;
        this.account=account;
        this.staffOrganisation = staffOrganisation;
        this.enterprise=enterprise;
        this.network=network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudeoilTxt = new javax.swing.JTextField();
        mercuryTxt = new javax.swing.JTextField();
        recordWaterReadingsBtn = new javax.swing.JButton();
        uraniumTxt = new javax.swing.JTextField();
        leadlbl = new javax.swing.JLabel();
        plasticTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        leadTxt = new javax.swing.JTextField();
        plasticlbl = new javax.swing.JLabel();
        testDateLbl = new javax.swing.JLabel();
        uraniumlbl = new javax.swing.JLabel();
        mercurylbl = new javax.swing.JLabel();
        oillbl = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JLabel();
        userlbl = new javax.swing.JLabel();
        EmployeeWorkArealbl = new javax.swing.JLabel();
        PageTitlelbl = new javax.swing.JLabel();
        testDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 255, 255));

        recordWaterReadingsBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        recordWaterReadingsBtn.setText("Record Values");
        recordWaterReadingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordWaterReadingsBtnActionPerformed(evt);
            }
        });

        leadlbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        leadlbl.setText("Lead : ");

        backBtn.setBackground(new java.awt.Color(204, 255, 255));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backBtn.setText("<< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        plasticlbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        plasticlbl.setText("Plastic :");

        testDateLbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        testDateLbl.setText("Test Date : ");

        uraniumlbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        uraniumlbl.setText("Uranium : ");

        mercurylbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mercurylbl.setText("Mercury :");

        oillbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        oillbl.setText("Crude Oil : ");

        userlbl.setText("User:");

        EmployeeWorkArealbl.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        EmployeeWorkArealbl.setText("Employee DashBoard");

        PageTitlelbl.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        PageTitlelbl.setText("Lab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(leadlbl)
                                .addComponent(oillbl)
                                .addComponent(mercurylbl))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(crudeoilTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mercuryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(125, 125, 125)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(plasticlbl)
                                .addComponent(uraniumlbl)
                                .addComponent(testDateLbl))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(uraniumTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(plasticTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(testDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(427, 427, 427)
                            .addComponent(PageTitlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(226, 226, 226)
                        .addComponent(recordWaterReadingsBtn)
                        .addGap(101, 101, 101)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmployeeWorkArealbl)
                .addGap(78, 78, 78)
                .addComponent(userlbl)
                .addGap(18, 18, 18)
                .addComponent(usernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageTitlelbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeWorkArealbl)
                    .addComponent(userlbl)
                    .addComponent(usernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plasticlbl)
                            .addComponent(plasticTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uraniumlbl)
                            .addComponent(uraniumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(testDateLbl)
                            .addComponent(testDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leadlbl)
                            .addComponent(leadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mercuryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mercurylbl))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oillbl)
                            .addComponent(crudeoilTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordWaterReadingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(409, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recordWaterReadingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordWaterReadingsBtnActionPerformed

        request.setLeadReading(Double.parseDouble(leadTxt.getText()));
        request.setMercuryReading(Double.parseDouble(mercuryTxt.getText()));
        request.setCrudeOilReading(Double.parseDouble(crudeoilTxt.getText()));
        request.setPlasticReading(Double.parseDouble(plasticTxt.getText()));
        request.setUraniumReading(Double.parseDouble(uraniumTxt.getText()));
        request.setTestRecordDate(testDateChooser.getDate());
        
        request.setStatus("Complete");
        //request.setSenderEnterprise(enterprise.getEnterpriseType().getValue());
        
        JOptionPane.showMessageDialog(null, "Results are submitted", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_recordWaterReadingsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabScientistWorkAreaJPanel labSci = (LabScientistWorkAreaJPanel) component;
        labSci.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeWorkArealbl;
    private javax.swing.JLabel PageTitlelbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField crudeoilTxt;
    private javax.swing.JTextField leadTxt;
    private javax.swing.JLabel leadlbl;
    private javax.swing.JTextField mercuryTxt;
    private javax.swing.JLabel mercurylbl;
    private javax.swing.JLabel oillbl;
    private javax.swing.JTextField plasticTxt;
    private javax.swing.JLabel plasticlbl;
    private javax.swing.JButton recordWaterReadingsBtn;
    private com.toedter.calendar.JDateChooser testDateChooser;
    private javax.swing.JLabel testDateLbl;
    private javax.swing.JTextField uraniumTxt;
    private javax.swing.JLabel uraniumlbl;
    private javax.swing.JLabel userlbl;
    private javax.swing.JLabel usernamelbl;
    // End of variables declaration//GEN-END:variables
}
