/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HeadScientistOrganisation;
import Business.Organization.Organization;
import Business.Organization.staffOrganisation;
import Business.Organization.supervisorOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.SoilTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cc130tx
 */
public class ProcessSoilWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessSoilWorkRequestJPanel
     */
    JPanel userProcessContainer;
    SoilTestWorkRequest request;
    Network network;
    Enterprise enterprise;
    UserAccount userAccount;

    ProcessSoilWorkRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network, SoilTestWorkRequest request) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.request = request;
         this.network = network;
         this.enterprise = enterprise;
         this.userAccount = userAccount;
         locationjText.setText(request.getLocation());
         areaTextField.setText(request.getArea());
         jLabel3.setVisible(false);
         jComboBox2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        locationjText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        backButton = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        AreaLabel = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("             FIELD DATA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 270, 41));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 78, 24));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Location");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 71, 24));

        locationjText.setEditable(false);
        locationjText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(locationjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "500 grams", "700 grams", "800 grams", "1 Kg", "1.5 Kg" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 130, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 82, -1));

        jDateChooser1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 130, -1));

        backButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 100, 39));

        submitButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        submitButton1.setText("Submit");
        submitButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 96, 39));

        AreaLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        AreaLabel.setText("Area");
        add(AreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, -1));

        areaTextField.setEditable(false);
        areaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(areaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, -1));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("Send to Lab");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, 40));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Receiver");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 104, 22));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        StaffWorkAreaJPanel dwjp = (StaffWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        // TODO add your handling code here:
        
        request.setArea(areaTextField.getText());
        request.setLocation(locationjText.getText());
        request.setQuantity(String.valueOf(jComboBox1.getSelectedItem()));
        request.setDate(jDateChooser1.getDate());
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(null, "Request processed", "Success", JOptionPane.INFORMATION_MESSAGE);   
        
        //Forwarding the request to Lab
        //String enterpriseLab = null;
        
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) 
        {
            if(e.getEnterpriseType().getValue().equalsIgnoreCase("lab"))
            {
                //enterpriseLab = e.getEnterpriseType().getValue();
                jComboBox2.addItem(e);
                break;
            }
            else
            {
                continue;
            }  
        }
        
         jLabel3.setVisible(true);
         jComboBox2.setVisible(true);
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Organization org = null;
        
        Enterprise elab = (Enterprise)jComboBox2.getSelectedItem();
        
        for (Organization organization : elab.getOrganizationDirectory().getOrganizationList())
        {
            if (organization instanceof HeadScientistOrganisation){ //supervisorOrganisation){
                org = organization;
                //System.out.println(org.getName());
                break;
                  }
        }
        
        //System.out.println("2"+org.getName());
        if (org!=null)
        {
            //System.out.println(userAccount.getUsername());
            org.getWorkQueue().getWorkRequestList().add(request);
            //System.out.println("2"+org.getName());
            //System.out.println(org.getWorkQueue().getWorkRequestList().size());
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            
            JOptionPane.showMessageDialog(null, "Data Send to Lab", "Success", JOptionPane.INFORMATION_MESSAGE);    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField locationjText;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
