/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import userinterface.NetworkAdminWorkArea.ManageEnterpriseJPanel;
import userinterface.NetworkAdminWorkArea.ManageEnterpriseAdminJPanel;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Network network;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system,Network network, UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=system;
        this.network = network;
        this.account= account;
        
        populateTable();
        
        userAccountLabel.setText(account.getUsername());
    }

    
   
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        
        for (Network network : ecosystem.getNetworkList()) {
           /* System.out.println(network.getName());
            System.out.println(network.getEmployeeDirectory());*/
            
            for (Employee employee : network.getEmployeeDirectory().getEmployeeList()) {
               // System.out.println(employee.getName());
                
                for (UserAccount userAccount : network.getUserAccountDirectory().getUserAccountList()) {
                   // System.out.println(userAccount.getUsername());
                    Object[] row = new Object[3];
                    row[0] = network.getName();
                    row[1] = employee.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        userAccountLabel = new javax.swing.JLabel();
        manageWorkarea = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        btnManageNetwork = new javax.swing.JButton();
        manageNetworkAdmin = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("User Account");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 50));

        userAccountLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        userAccountLabel.setText("<Value>");
        add(userAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 36, 110, 40));

        manageWorkarea.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        manageWorkarea.setText("My Work Area");
        manageWorkarea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageWorkarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWorkareaActionPerformed(evt);
            }
        });
        add(manageWorkarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 70));

        networkJTable.setBackground(new java.awt.Color(204, 204, 255));
        networkJTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        networkJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Network Head Name", "Network Head UserName"
            }
        ));
        networkJTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane.setViewportView(networkJTable);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 490, 220));

        btnManageNetwork.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 190, 70));

        manageNetworkAdmin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        manageNetworkAdmin.setText("Manage Network Admins");
        manageNetworkAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageNetworkAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkAdminActionPerformed(evt);
            }
        });
        add(manageNetworkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 190, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void manageWorkareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWorkareaActionPerformed
        // TODO add your handling code here:
        SysadminWorkArea SysadminWorkArea=new SysadminWorkArea(userProcessContainer, ecosystem,network,account);
        userProcessContainer.add("SysadminWorkArea",SysadminWorkArea);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
    }//GEN-LAST:event_manageWorkareaActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
                ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void manageNetworkAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkAdminActionPerformed
        // TODO add your handling code here:
        ManageNetworkAdminJPanel manageNetworkAdminJPanel=new ManageNetworkAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkAdminJPanel",manageNetworkAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JToggleButton manageNetworkAdmin;
    private javax.swing.JToggleButton manageWorkarea;
    private javax.swing.JTable networkJTable;
    private javax.swing.JLabel userAccountLabel;
    // End of variables declaration//GEN-END:variables
}
